"""
Embedding vector model for RAG retrieval validation system.
"""
from dataclasses import dataclass
from typing import List
import hashlib


@dataclass
class EmbeddingVector:
    """
    Numerical representation of text content generated by Cohere models for semantic comparison.
    """
    vector: List[float]
    model_version: str
    dimensions: int
    text_hash: str

    def __post_init__(self):
        """
        Validate the embedding vector after initialization.
        """
        if not isinstance(self.vector, list):
            raise ValueError("Vector must be a list of floats")

        if len(self.vector) != self.dimensions:
            raise ValueError(f"Vector length {len(self.vector)} does not match expected dimensions {self.dimensions}")

        # Check that all values are numbers
        for i, val in enumerate(self.vector):
            if not isinstance(val, (int, float)):
                raise ValueError(f"Vector contains non-numeric value at index {i}: {val}")

            # Check for NaN or infinity
            if val != val:  # Check for NaN (NaN != NaN is True)
                raise ValueError(f"Vector contains NaN value at index {i}")

            if val == float('inf') or val == float('-inf'):
                raise ValueError(f"Vector contains infinity value at index {i}")

        if not self.model_version.strip():
            raise ValueError("Model version must not be empty")

        if self.dimensions <= 0:
            raise ValueError("Dimensions must be positive")